name = "CatppuccinMakieThemes"
uuid = "c37c50e1-20da-4a65-b669-80e6e9abe7a3"
authors = ["Felix <felixgerick@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
